### ISSUE TITLE
Is this for Glide v3?

### ISSUE THREAD

**Issue by Rainer-Lang** [thedeveloperworldisyours/RoundedConersWithGlide#1]
Could you provide a version for Glide v4 - with colored borders?

**Comment by JavierGonzal** [comment]
I updated for Glide 4, but I don't understand with colored borders. Can you explain more, please?

**Comment by Rainer-Lang** [comment]
Thanks for updating to v4.

Colored border:
I need a border around the image. Thickness is 2dp and the color should be variable too (sometimes blue and sometimes red).

**Comment by JavierGonzal** [comment]
Hi again,

Now We can specify corner, margin ,border color and border margin:

```
public static int sCorner = 15;
public static int sMargin = 20;

public static int sBorder = 10;
public static String sColor = "#7D9067";
```
with this constructor:

```
Glide.with(this).load("http://scareface.jpeg")
        .apply(RequestOptions.bitmapTransform(
        new RoundedCornersTransformation(this, sCorner, sMargin, sColor, sBorder))).into(mImageViewBorder);
```

I hope to help you with this change.

**Comment by Rainer-Lang** [comment]
Thanks

**Comment by Rainer-Lang** [comment]
@CabezasGonzalezJavier If I define a border/margin, the image inside stays the the same size. So the visible image is not all visible anymore.
You could even see this effect on your image in the readme.

I think the image inside should be scaled.

**Comment by JavierGonzal** [comment]
Hello,
I made changes, now if you want to add visible all image, you can put `margin = 0`
And for the (frame/border), in drawable you should add this .xml:

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <solid android:color="@android:color/transparent" />
    <stroke
        android:width="15dp"
        android:color="#7D9067" />

    <corners android:radius="5dp" />
</shape>
```
In your layout, two elements:

```
<RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/circle"
        app:layout_constraintBottom_toTopOf="@+id/guideline"
        app:layout_constraintLeft_toLeftOf="@+id/guideline3"
        app:layout_constraintRight_toLeftOf="@+id/guideline3"
        app:layout_constraintTop_toTopOf="@+id/guideline">

        <ImageView
            android:id="@+id/imageViewBorderResizing"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:srcCompat="@mipmap/ic_launcher" />
</RelativeLayout>
```

In your Activity or fragment you can this parametres

```
public static int sCorner = 15;
public static int sMargin = 0;
```
with this constructor:
```
Glide.with(this).load("http://thedeveloperworldisyours.com/wp-content/uploads/scareface.jpeg").apply(RequestOptions.bitmapTransform(new RoundedCornersTransformation(this, sCorner, sMargin))).into(mImageViewBorderResizing);
```

So now in this repository you can choose three options.

I hope to help you with this change.

**Comment by Rainer-Lang** [comment]
@CabezasGonzalezJavier Thanks!
